### ISSUE TITLE
React 为什么会流行？

### ISSUE THREAD

**Issue by LeezQ** [frontend9/fe9-library#17]
react是在13年左右开始开源的第一个版本，为什么 react 能取代我们之前用的 jQuery 这样的开发库，成为然后随着其开发理念和ReactNative这样的跨端研发库，使得 react 迅速成为最受欢迎的前端开发框架？

我们回顾下，在没有 react 这样的框架之前，我们使用 jQuery 来做前端开发的时候是什么样的、
举个简单的场景，
页面上有个按钮，点击后数字 +1，
```
<span>1</span> <a>+</a>
```
使用 jQuery，我们的代码大概是下面这样的：
```
$('a').on('click', () => {
 let num = parseInt($('span').text(), 10);
 $('span').text(++num);
});
```
这是在 jquery 时期很常见的代码，当时写这些代码的时候并没有觉得有什么问题，反而操作dom 的方式显得非常直观，开发者仅需要在页面上通过 获取元素，然后操作 dom 的元素即可。另外 jQuery 封装了很多的浏览器兼容性问题，让每个浏览器下的都有标准的  api 接口。
那么这种以 dom 为主的开发方式会带来什么问题呢？现在回过头去看，是能看到一些问题的，以dom为视角的开发，很多情况下是将后端渲染后的页面去做一些点缀性的交互操作。那这种交互操作对于开发的人来说，其实是很散的。在代码层面，完全看不到相关的逻辑关系。比如：

```
option.js

// 点击 a 按钮的时候的操作
$('.class_a').click(function() {
  // code...
});
// 点击 b 按钮的时候的操作
$('.class_a .class_b').click(function() {
  // code...
});
```

从这段代码里我们并不能看到这些 dom 操作跟我当前页面有什么关系，而更像是挂载在页面上的一段段贴片脚本，另外由于后端代码和前端的脚本是分开在不同的地方，那么当后端代码把相关的 dom 元素删除之后，很多情况下，我们并没有意识要去删除一些相关的无用的 js 代码，这会导致后续随着项目工程的越来越大，无效代码也越来越多。

那么这个问题怎么解，一个方式就是组件化，在那个年代，有很多的团队也在在这样的事情，只是那时候的方式是按照就近原则把相关的文件聚在一起，比较有名的是两个方案：一个是以 backbone 为主的 mvc 框架，一个是 facebook 的bigpipe，其实 backbone 或者 bigpipe 已经离现在的这种数据流为主的框架至少从代码结构层面已经很接近了。从工程维护的角度来讲，也都是一样的思路。那么为什么在这之后还会有 react 这样的框架出来？

很重要的一点是之前的这些框架，从思路上来说还是以 dom 操作为主，页面的渲染是一次性的，可以是后端渲染，也可以是前端通过模板引擎来渲染，但是后续的交互还是通过 dom 操作来完成。

而 react 带来的思路是 view = f(data); 页面渲染是通过 data 驱动，后续的交互操作也是通过 data 的变更来展示页面。

那这样的好处是什么呢？
1、前端与后端通过 json 来传递数据，可以方便的去做前后端分离。
2、组件化，让前端更易规模化和工程化
3、渲染层都由前端控制，且通过 virtual dom 让渲染更高效
4、页面的渲染通过数据驱动，页面变成了一个状态机，从而让之前的那种操作 dom 的不可追溯源头的方式变得更易追踪是什么操作导致的页面变化。

几年前 jQuery 还很火，基本上每个网站都有 jQuery 或者 YUI 这样的框架来做的，但是现在这类的框架变成了过时的东西，其实从很多的框架为什么会变得流行，一般都是因为它创新的思路去解决问题的方法。对我们来说也是一样，我们去解决一个遗留问题的时候，我们能否换个思路，用创新的方法去解决，或许会能打开一片新的天地。

**Comment by freerollingcs** [comment]
精辟。作为前端小白来说，模块化的开发增加了代码复用率，简单好用
